# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addForm.ui'
#
# Created: Sat Jan 19 20:59:52 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_addDialog(object):
    def setupUi(self, addDialog):
        addDialog.setObjectName(_fromUtf8("addDialog"))
        addDialog.resize(660, 606)
        addDialog.setMinimumSize(QtCore.QSize(570, 385))
        addDialog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.verticalLayout_5 = QtGui.QVBoxLayout(addDialog)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.groupBox = QtGui.QGroupBox(addDialog)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setMinimumSize(QtCore.QSize(124, 0))
        self.label_2.setMaximumSize(QtCore.QSize(124, 16777215))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_17.addWidget(self.label_2)
        self.mierzonyParametr = QtGui.QLineEdit(self.groupBox)
        self.mierzonyParametr.setEnabled(True)
        self.mierzonyParametr.setObjectName(_fromUtf8("mierzonyParametr"))
        self.horizontalLayout_17.addWidget(self.mierzonyParametr)
        self.verticalLayout.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(124, 0))
        self.label_5.setMaximumSize(QtCore.QSize(124, 16777215))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        self.przyrzadPomiarowy = QtGui.QLineEdit(self.groupBox)
        self.przyrzadPomiarowy.setObjectName(_fromUtf8("przyrzadPomiarowy"))
        self.horizontalLayout_3.addWidget(self.przyrzadPomiarowy)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(119, 0))
        self.label_3.setMaximumSize(QtCore.QSize(124, 16777215))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.metodaPomiaru = QtGui.QComboBox(self.groupBox)
        self.metodaPomiaru.setObjectName(_fromUtf8("metodaPomiaru"))
        self.metodaPomiaru.addItem(_fromUtf8(""))
        self.metodaPomiaru.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.metodaPomiaru)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setMinimumSize(QtCore.QSize(124, 0))
        self.label_4.setMaximumSize(QtCore.QSize(124, 16777215))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_16.addWidget(self.label_4)
        self.rodzajZapisuDanych = QtGui.QComboBox(self.groupBox)
        self.rodzajZapisuDanych.setObjectName(_fromUtf8("rodzajZapisuDanych"))
        self.rodzajZapisuDanych.addItem(_fromUtf8(""))
        self.rodzajZapisuDanych.addItem(_fromUtf8(""))
        self.rodzajZapisuDanych.addItem(_fromUtf8(""))
        self.horizontalLayout_16.addWidget(self.rodzajZapisuDanych)
        self.verticalLayout.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setMinimumSize(QtCore.QSize(124, 0))
        self.label_7.setMaximumSize(QtCore.QSize(124, 16777215))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_15.addWidget(self.label_7)
        self.cechyWykresu = QtGui.QLineEdit(self.groupBox)
        self.cechyWykresu.setObjectName(_fromUtf8("cechyWykresu"))
        self.horizontalLayout_15.addWidget(self.cechyWykresu)
        self.verticalLayout.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setMinimumSize(QtCore.QSize(124, 0))
        self.label_6.setMaximumSize(QtCore.QSize(124, 16777215))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_4.addWidget(self.label_6)
        self.jednostkaPomiarowa = QtGui.QLineEdit(self.groupBox)
        self.jednostkaPomiarowa.setObjectName(_fromUtf8("jednostkaPomiarowa"))
        self.horizontalLayout_4.addWidget(self.jednostkaPomiarowa)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setMinimumSize(QtCore.QSize(124, 0))
        self.label_8.setMaximumSize(QtCore.QSize(124, 16777215))
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_14.addWidget(self.label_8)
        self.dokladnoscPomiarowa = QtGui.QLineEdit(self.groupBox)
        self.dokladnoscPomiarowa.setObjectName(_fromUtf8("dokladnoscPomiarowa"))
        self.horizontalLayout_14.addWidget(self.dokladnoscPomiarowa)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_14 = QtGui.QLabel(self.groupBox)
        self.label_14.setMinimumSize(QtCore.QSize(124, 0))
        self.label_14.setMaximumSize(QtCore.QSize(124, 16777215))
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_5.addWidget(self.label_14)
        self.skalaPomiaru = QtGui.QLineEdit(self.groupBox)
        self.skalaPomiaru.setObjectName(_fromUtf8("skalaPomiaru"))
        self.horizontalLayout_5.addWidget(self.skalaPomiaru)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_13 = QtGui.QLabel(self.groupBox)
        self.label_13.setMinimumSize(QtCore.QSize(124, 0))
        self.label_13.setMaximumSize(QtCore.QSize(124, 16777215))
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_13.addWidget(self.label_13)
        self.lokalizacja = QtGui.QLineEdit(self.groupBox)
        self.lokalizacja.setObjectName(_fromUtf8("lokalizacja"))
        self.horizontalLayout_13.addWidget(self.lokalizacja)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_11 = QtGui.QLabel(self.groupBox)
        self.label_11.setMinimumSize(QtCore.QSize(124, 0))
        self.label_11.setMaximumSize(QtCore.QSize(124, 16777215))
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_6.addWidget(self.label_11)
        self.miejsce = QtGui.QLineEdit(self.groupBox)
        self.miejsce.setObjectName(_fromUtf8("miejsce"))
        self.horizontalLayout_6.addWidget(self.miejsce)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_12 = QtGui.QLabel(self.groupBox)
        self.label_12.setMinimumSize(QtCore.QSize(124, 0))
        self.label_12.setMaximumSize(QtCore.QSize(124, 16777215))
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_12.addWidget(self.label_12)
        self.obserwator = QtGui.QLineEdit(self.groupBox)
        self.obserwator.setObjectName(_fromUtf8("obserwator"))
        self.horizontalLayout_12.addWidget(self.obserwator)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_15 = QtGui.QLabel(self.groupBox)
        self.label_15.setMinimumSize(QtCore.QSize(124, 0))
        self.label_15.setMaximumSize(QtCore.QSize(124, 16777215))
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_8.addWidget(self.label_15)
        self.czestotliwoscPomiaru = QtGui.QLineEdit(self.groupBox)
        self.czestotliwoscPomiaru.setObjectName(_fromUtf8("czestotliwoscPomiaru"))
        self.horizontalLayout_8.addWidget(self.czestotliwoscPomiaru)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_16 = QtGui.QLabel(self.groupBox)
        self.label_16.setMinimumSize(QtCore.QSize(124, 0))
        self.label_16.setMaximumSize(QtCore.QSize(124, 16777215))
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_10.addWidget(self.label_16)
        self.stacjaPomiarowa = QtGui.QComboBox(self.groupBox)
        self.stacjaPomiarowa.setObjectName(_fromUtf8("stacjaPomiarowa"))
        self.stacjaPomiarowa.addItem(_fromUtf8(""))
        self.stacjaPomiarowa.addItem(_fromUtf8(""))
        self.horizontalLayout_10.addWidget(self.stacjaPomiarowa)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_17 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setMinimumSize(QtCore.QSize(124, 0))
        self.label_17.setMaximumSize(QtCore.QSize(124, 16777215))
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_9.addWidget(self.label_17)
        self.uwagi = QtGui.QTextEdit(self.groupBox)
        self.uwagi.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.uwagi.setObjectName(_fromUtf8("uwagi"))
        self.horizontalLayout_9.addWidget(self.uwagi)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.applyMetadata = QtGui.QPushButton(self.groupBox)
        self.applyMetadata.setObjectName(_fromUtf8("applyMetadata"))
        self.verticalLayout.addWidget(self.applyMetadata)
        self.horizontalLayout_18.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(addDialog)
        self.groupBox_2.setEnabled(False)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.listWidget = QtGui.QListWidget(self.groupBox_2)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.verticalLayout_2.addWidget(self.listWidget)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btnDel = QtGui.QPushButton(self.groupBox_2)
        self.btnDel.setEnabled(False)
        self.btnDel.setObjectName(_fromUtf8("btnDel"))
        self.horizontalLayout.addWidget(self.btnDel)
        self.btnAdd = QtGui.QPushButton(self.groupBox_2)
        self.btnAdd.setEnabled(False)
        self.btnAdd.setObjectName(_fromUtf8("btnAdd"))
        self.horizontalLayout.addWidget(self.btnAdd)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.nowyPomiar = QtGui.QGroupBox(self.groupBox_2)
        self.nowyPomiar.setEnabled(False)
        self.nowyPomiar.setObjectName(_fromUtf8("nowyPomiar"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.nowyPomiar)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_9 = QtGui.QLabel(self.nowyPomiar)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_11.addWidget(self.label_9)
        self.dateEdit = QtGui.QDateEdit(self.nowyPomiar)
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.horizontalLayout_11.addWidget(self.dateEdit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label = QtGui.QLabel(self.nowyPomiar)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_3.addWidget(self.label)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.pathEdit = QtGui.QLineEdit(self.nowyPomiar)
        self.pathEdit.setEnabled(False)
        self.pathEdit.setObjectName(_fromUtf8("pathEdit"))
        self.horizontalLayout_7.addWidget(self.pathEdit)
        self.btnBrowse = QtGui.QToolButton(self.nowyPomiar)
        self.btnBrowse.setObjectName(_fromUtf8("btnBrowse"))
        self.horizontalLayout_7.addWidget(self.btnBrowse)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.btnApply = QtGui.QPushButton(self.nowyPomiar)
        self.btnApply.setEnabled(False)
        self.btnApply.setObjectName(_fromUtf8("btnApply"))
        self.verticalLayout_3.addWidget(self.btnApply)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addWidget(self.nowyPomiar)
        self.horizontalLayout_18.addWidget(self.groupBox_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem)
        self.btnOK = QtGui.QPushButton(addDialog)
        self.btnOK.setEnabled(False)
        self.btnOK.setMinimumSize(QtCore.QSize(125, 0))
        self.btnOK.setObjectName(_fromUtf8("btnOK"))
        self.horizontalLayout_26.addWidget(self.btnOK)
        self.btnCancel = QtGui.QPushButton(addDialog)
        self.btnCancel.setMinimumSize(QtCore.QSize(125, 0))
        self.btnCancel.setObjectName(_fromUtf8("btnCancel"))
        self.horizontalLayout_26.addWidget(self.btnCancel)
        self.verticalLayout_5.addLayout(self.horizontalLayout_26)

        self.retranslateUi(addDialog)
        self.metodaPomiaru.setCurrentIndex(0)
        self.stacjaPomiarowa.setCurrentIndex(0)
        QtCore.QObject.connect(self.btnCancel, QtCore.SIGNAL(_fromUtf8("clicked()")), addDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(addDialog)

    def retranslateUi(self, addDialog):
        addDialog.setWindowTitle(_translate("addDialog", "Dodaj pomiar", None))
        self.groupBox.setTitle(_translate("addDialog", "Metadane pomiaru", None))
        self.label_2.setText(_translate("addDialog", "Mierzony parametr", None))
        self.mierzonyParametr.setText(_translate("addDialog", "Opad atmosferyczny", None))
        self.label_5.setText(_translate("addDialog", "Przyrząd pomiarowy", None))
        self.przyrzadPomiarowy.setText(_translate("addDialog", "Pluwiograf", None))
        self.label_3.setText(_translate("addDialog", "Metoda pomiaru", None))
        self.metodaPomiaru.setItemText(0, _translate("addDialog", "Automat", None))
        self.metodaPomiaru.setItemText(1, _translate("addDialog", "Tradycyjna", None))
        self.label_4.setText(_translate("addDialog", "Rodzaj zapisu danych", None))
        self.rodzajZapisuDanych.setItemText(0, _translate("addDialog", "Dziennik", None))
        self.rodzajZapisuDanych.setItemText(1, _translate("addDialog", "Samopis analogowy", None))
        self.rodzajZapisuDanych.setItemText(2, _translate("addDialog", "Samopis cyfrowy", None))
        self.label_7.setText(_translate("addDialog", "Cechy wykresu", None))
        self.cechyWykresu.setText(_translate("addDialog", "1 dniowe paski", None))
        self.label_6.setText(_translate("addDialog", "Jednostka pomiarowa", None))
        self.jednostkaPomiarowa.setText(_translate("addDialog", "[mm]", None))
        self.label_8.setText(_translate("addDialog", "Dokładność pomiarowa", None))
        self.dokladnoscPomiarowa.setText(_translate("addDialog", "0,1 mm", None))
        self.label_14.setText(_translate("addDialog", "Skala pomiaru", None))
        self.skalaPomiaru.setText(_translate("addDialog", "1-10 mm", None))
        self.label_13.setText(_translate("addDialog", "Lokalizacja", None))
        self.label_11.setText(_translate("addDialog", "Miejsce", None))
        self.label_12.setText(_translate("addDialog", "Obserwator", None))
        self.label_15.setText(_translate("addDialog", "Częstotliwość pomiaru", None))
        self.czestotliwoscPomiaru.setText(_translate("addDialog", "Ciągły", None))
        self.label_16.setText(_translate("addDialog", "Stacja pomiarowa", None))
        self.stacjaPomiarowa.setItemText(0, _translate("addDialog", "Czynna", None))
        self.stacjaPomiarowa.setItemText(1, _translate("addDialog", "Nieczynna", None))
        self.label_17.setText(_translate("addDialog", "Uwagi", None))
        self.applyMetadata.setText(_translate("addDialog", "Zapisz metadane", None))
        self.groupBox_2.setTitle(_translate("addDialog", "Pomiary", None))
        self.btnDel.setText(_translate("addDialog", "Usuń pomiar", None))
        self.btnAdd.setText(_translate("addDialog", "Nowy pomiar", None))
        self.nowyPomiar.setTitle(_translate("addDialog", "Nowy pomiar", None))
        self.label_9.setText(_translate("addDialog", "Data pomiaru", None))
        self.label.setText(_translate("addDialog", "Plik wykresu", None))
        self.btnBrowse.setText(_translate("addDialog", "...", None))
        self.btnApply.setText(_translate("addDialog", "Dodaj", None))
        self.btnOK.setText(_translate("addDialog", "Zatwierdź", None))
        self.btnCancel.setText(_translate("addDialog", "Anuluj", None))

